### ISSUE TITLE
Requesting the filtered ground-truth variants

### ISSUE THREAD

**Issue by huangnengCSU** [vladimirsouza/lrRNAseqVariantCalling#5]
Hi,
    Thanks for the useful variant calling tool for long-read RNA sequencing data. Since the entire tool and the evaluation process are developed in R language, it may be difficult for users who are not familiar with R language. Could you please release the ground-truth variants of WTC-11 dataset (filtered by short-read variant density and short-read coverage)? So that we don't have to download the huge short-read bam and run the time-consuming steps to calculate the bam's depth.

Best,
Neng

**Comment by vladimirsouza** [comment]
Hi [huangnengCSU](https://github.com/huangnengCSU),

Sorry for the late reply.

Our tool is built in R but you can run the entire pipeline using the terminal command line. See a tutorial [here](https://github.com/vladimirsouza/lrRNAseqVariantCalling?tab=readme-ov-file#how-to-call-genetic-variants-from-iso-seq-data-using-our-pipeline).

The ground-truth VCF file for WTC11 that we used in this work can be downloaded from the [Allen Institute](https://open.quiltdata.com/b/allencell/tree/aics/wtc11_short_read_genome_sequence/variants/), as described in the [Availability of data and materials](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-023-02923-y#availability-of-data-and-materials) section of our paper. Before using this VCF file as the ground-truth, we did some filtering on it, which we showed [here](https://github.com/vladimirsouza/lrRNAseqVariantCalling/blob/main/variant_calling_code/isoseq/2_generate_ground_truth/wtc11/groundTruth_wtc11_downloaded.sh).

**Comment by huangnengCSU** [comment]
Thanks. But could you share the filtered ground truth vcf file of WTC11 and jurkat on zenodo? This will make it easier to follow your work.
